spring.config.import=.env[.properties]

spring.application.name=TaskManager
server.servlet.context-path=/api

# DB settings
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.liquibase.change-log=config/liquibase/master.xml
spring.liquibase.enabled=true

# Security
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
